name: C/C++

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
          - os: macos-latest
            target: x86_64-apple-darwin
          #- os: ubuntu-latest
          #  target: x86_64-unknown-linux-musl
          - os: windows-latest
            target: x86_64-pc-windows-msvc

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Install toolchain
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          default: true
          target: ${{ matrix.target }}
    - name: Build
      run: cmake -S fourier-ffi -B build -G "Unix Makefiles" && make -C build
      shell: bash
    - name: Test
      run: make -C build test
      shell: bash
    - name: Package
      run: make -C build package
      shell: bash
